### ISSUE TITLE
这种部署报错该如何解决呢Error: Command "pnpm run build" exited with 1

### ISSUE THREAD

**Issue by harleyszhang** [tw93/tw93.github.io#191]
[22:10:20.119] Running build in Washington, D.C., USA (East) – iad1
[22:10:20.279] Cloning github.com/HarleysZhang/harleyszhang.github.io (Branch: master, Commit: 37708ce)
[22:10:20.428] Skipping build cache, deployment was triggered without cache.
[22:10:31.249] Cloning completed: 10.973s
[22:10:32.066] Running "vercel build"
[22:10:32.486] Vercel CLI 37.12.0
[22:10:33.492] Detected `pnpm-lock.yaml` version 9 generated by pnpm@9.x
[22:10:33.493] Installing dependencies...
[22:10:33.764] Bundler 2.5.15 is running, but your lockfile was generated with 2.5.6. Installing Bundler 2.5.6 and restarting using that version.
[22:10:34.581] Fetching gem metadata from https://rubygems.org/.
[22:10:34.588] Fetching bundler 2.5.6
[22:10:34.686] Installing bundler 2.5.6
[22:10:36.899] Fetching gem metadata from https://rubygems.org/...........
[22:10:36.935] Resolving dependencies...
[22:10:37.134] Fetching public_suffix 5.0.4
[22:10:39.904] Fetching colorator 1.1.0
[22:10:40.747] Installing public_suffix 5.0.4
[22:10:40.755] Fetching concurrent-ruby 1.2.3
[22:10:40.838] Installing colorator 1.1.0
[22:10:40.841] Fetching eventmachine 1.2.7
[22:10:41.064] Installing concurrent-ruby 1.2.3
[22:10:41.073] Installing eventmachine 1.2.7 with native extensions
[22:10:41.151] Fetching http_parser.rb 0.8.0
[22:10:41.170] Installing http_parser.rb 0.8.0 with native extensions
[22:10:44.272] Fetching ffi 1.16.3
[22:10:44.336] Installing ffi 1.16.3 with native extensions
[22:10:54.881] Fetching forwardable-extended 2.6.0
[22:10:54.909] Installing forwardable-extended 2.6.0
[22:10:54.918] Fetching google-protobuf 3.25.5 (x86_64-linux) (was 3.25.2)
[22:10:54.986] Installing google-protobuf 3.25.5 (x86_64-linux) (was 3.25.2)
[22:10:55.023] Fetching rb-fsevent 0.11.2
[22:10:55.032] Installing rb-fsevent 0.11.2
[22:10:55.043] Fetching rexml 3.2.6
[22:10:55.056] Installing rexml 3.2.6
[22:10:55.074] Fetching liquid 4.0.4
[22:10:55.086] Installing liquid 4.0.4
[22:10:55.108] Fetching mercenary 0.4.0
[22:10:55.117] Installing mercenary 0.4.0
[22:10:55.127] Fetching rouge 4.2.0
[22:10:55.218] Installing rouge 4.2.0
[22:10:55.376] Fetching safe_yaml 1.0.5
[22:10:55.385] Installing safe_yaml 1.0.5
[22:10:55.402] Fetching unicode-display_width 2.5.0
[22:10:55.408] Installing unicode-display_width 2.5.0
[22:10:55.416] Fetching webrick 1.8.1
[22:10:55.425] Installing webrick 1.8.1
[22:10:55.439] Fetching jekyll-paginate 1.1.0
[22:10:55.449] Installing jekyll-paginate 1.1.0
[22:10:55.458] Fetching addressable 2.8.6
[22:10:55.470] Installing addressable 2.8.6
[22:10:55.487] Fetching i18n 1.14.1
[22:10:55.497] Installing i18n 1.14.1
[22:10:55.511] Fetching rb-inotify 0.10.1
[22:10:55.518] Installing rb-inotify 0.10.1
[22:10:55.527] Fetching pathutil 0.16.2
[22:10:55.534] Installing pathutil 0.16.2
[22:10:55.543] Fetching sass-embedded 1.70.0 (x86_64-linux-gnu)
[22:10:55.697] Installing sass-embedded 1.70.0 (x86_64-linux-gnu)
[22:10:55.825] Fetching kramdown 2.4.0
[22:10:55.869] Installing kramdown 2.4.0
[22:10:56.081] Fetching terminal-table 3.0.2
[22:10:56.095] Installing terminal-table 3.0.2
[22:10:56.107] Fetching listen 3.8.0
[22:10:56.129] Installing listen 3.8.0
[22:10:56.146] Fetching jekyll-sass-converter 3.0.0
[22:10:56.158] Installing jekyll-sass-converter 3.0.0
[22:10:56.162] Fetching kramdown-parser-gfm 1.1.0
[22:10:56.168] Installing kramdown-parser-gfm 1.1.0
[22:10:56.181] Fetching jekyll-watch 2.2.1
[22:10:56.192] Installing jekyll-watch 2.2.1
[22:11:00.305] Fetching em-websocket 0.5.3
[22:11:00.322] Installing em-websocket 0.5.3
[22:11:00.334] Fetching jekyll 4.3.3
[22:11:00.347] Installing jekyll 4.3.3
[22:11:00.368] Fetching jekyll-feed 0.17.0
[22:11:00.369] Fetching jekyll-pdf-embed 1.1.3
[22:11:00.377] Installing jekyll-feed 0.17.0
[22:11:00.381] Installing jekyll-pdf-embed 1.1.3
[22:11:00.385] Fetching jekyll-sitemap 1.4.0
[22:11:00.395] Installing jekyll-sitemap 1.4.0
[22:11:00.408] Bundle complete! 5 Gemfile dependencies, 34 gems now installed.
[22:11:00.409] Bundled gems are installed into `./vendor/bundle`
[22:11:00.453] Installing dependencies...
[22:11:01.594] Lockfile is up to date, resolution step is skipped
[22:11:01.610] Progress: resolved 1, reused 0, downloaded 0, added 0
[22:11:01.621] Packages: +17
[22:11:01.622] +++++++++++++++++
[22:11:01.950] Progress: resolved 17, reused 0, downloaded 17, added 17, done
[22:11:01.979] 
[22:11:01.980] devDependencies:
[22:11:01.980] + uglify-js 2.8.29
[22:11:01.980] 
[22:11:01.984] Done in 1.2s
[22:11:02.066] Running "pnpm run build"
[22:11:02.764] 
[22:11:02.765] > tw93@ build /vercel/path0
[22:11:02.765] > bundle exec jekyll build
[22:11:02.765] 
[22:11:03.302] /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll.rb:28: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of jekyll-4.3.3 to add csv into its gemspec.
[22:11:03.475] /vercel/path0/vendor/bundle/ruby/3.3.0/gems/safe_yaml-1.0.5/lib/safe_yaml/transform.rb:1: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of safe_yaml-1.0.5 to add base64 into its gemspec.
[22:11:03.497] /vercel/path0/vendor/bundle/ruby/3.3.0/gems/liquid-4.0.4/lib/liquid/standardfilters.rb:2: warning: bigdecimal was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec. Also contact author of liquid-4.0.4 to add bigdecimal into its gemspec.
[22:11:03.629] Configuration file: /vercel/path0/_config.yml
[22:11:03.658]             Source: /vercel/path0
[22:11:03.658]        Destination: /vercel/path0/_site
[22:11:03.659]  Incremental build: disabled. Enable with --incremental
[22:11:03.659]       Generating... 
[22:11:03.710] [33m           Warning: Excerpt modified in _posts/2024-09-09-future.md![0m
[22:11:03.710] [33m                    Found a Liquid block containing the excerpt separator "\n\n".[0m
[22:11:03.710] [33m                    The block has been modified with the appropriate closing tag.[0m
[22:11:03.711] [33m                    Feel free to define a custom excerpt or excerpt_separator in the[0m
[22:11:03.711] [33m                    document's Front Matter if the generated excerpt is unsatisfactory.[0m
[22:11:03.773]        Jekyll Feed: Generating feed for posts
[22:11:05.156] [31m                    ------------------------------------------------[0m
[22:11:05.157] [31m      Jekyll 4.3.3   Please append `--trace` to the `build` command [0m
[22:11:05.157] [31m                     for any additional information or backtrace. [0m
[22:11:05.157] [31m                    ------------------------------------------------[0m
[22:11:05.157] /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/url.rb:161:in `encode': "\xE6" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
[22:11:05.157] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/url.rb:161:in `unescape_path'
[22:11:05.157] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/static_file.rb:56:in `destination'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/cleaner.rb:60:in `block (2 levels) in new_files'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:364:in `block in each_site_file'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:364:in `each'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:364:in `each_site_file'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/cleaner.rb:60:in `block in new_files'
[22:11:05.158] 	from <internal:kernel>:90:in `tap'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/cleaner.rb:59:in `new_files'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/cleaner.rb:25:in `obsolete_files'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/cleaner.rb:15:in `cleanup!'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:221:in `cleanup'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:81:in `process'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
[22:11:05.158] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/exe/jekyll:15:in `<top (required)>'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `load'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
[22:11:05.159] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
[22:11:05.160] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
[22:11:05.160] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
[22:11:05.160] 	from /vercel/path0/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
[22:11:05.160] 	from /vercel/path0/vendor/bin/bundle:108:in `load'
[22:11:05.160] 	from /vercel/path0/vendor/bin/bundle:108:in `<main>'
[22:11:05.173]  ELIFECYCLE  Command failed with exit code 1.
[22:11:05.189] Error: Command "pnpm run build" exited with 1
[22:11:05.332] 

不是前端的，这种网站部署也是第一次接触，如果问题简单希望大佬赐教。

**Comment by harleyszhang** [comment]
已经解决了，目录内有中文pdf和 ppt，不支持 utf-8 编码，通过下述命令找到对应文件并删除.

`find . -name '*[! -~]*'`
